version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
#    env_file: ./src/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "8081"
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./src
    restart: unless-stopped
#    env_file: ./.env
    ports:
      - "8081"
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db: